---
version: '3.9'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "14"

services:
  traefik:
    image: traefik:v2.11.0
    restart: unless-stopped
    command:
      - "--log.format=json"
      - "--log.level=INFO"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging: *logging
  mariadb:
    image: mariadb:11.3.2
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=this-is-an-unsecure-password
      - MARIADB_USER=${ATUIN_DB_USERNAME}
      - MARIADB_PASSWORD=${ATUIN_DB_PASSWORD}
      - MARIADB_DATABASE=${ATUIN_DB_NAME}
      - MARIADB_UPGRADE=1
    healthcheck:
      test: mariadb-admin -u root -pthis-is-an-unsecure-password status
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./data/mariadb:/var/lib/mysql:Z
    logging: *logging
  natuin:
    image: natuin:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.natuin.loadbalancer.server.port=8080
      - traefik.http.routers.natuin.rule=PathPrefix(`/`)
      - traefik.http.routers.natuin.entrypoints=web
      - traefik.http.routers.natuin.service=natuin
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      mariadb:
        condition: service_healthy
    logging: *logging

